- name: "build package"
  shell: |
    cd /home/ubuntu/backend
    npm run build

- name: "run migrations and save status to https://memstash.io/"
  shell: |
    cd /home/ubuntu/backend
    npm run migrations > migrations.txt
    cat migrations.txt
    curl -H "Content-Type: text/plain" -H "token: de8dfebb-4853-48b3-88e7-67441f6ae6ad" --request PUT --data $( grep -c "No migrations are pending" migrations.txt ) https://api.memstash.io/values/migration_status

- name: "use pm2 to run the node server"
  shell: |
    cd /home/ubuntu/backend
    pm2 start npm -- run "start:dev"