Description: >
  Udapeople frontend stack

Parameters:
  ID:
    Description: Unique identifier
    Type: String

Resources:
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "udapeople-s3bucket-${ID}"
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: 404.html
  
  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref 'WebsiteBucket'
      PolicyDocument:
        Statement:
        - Sid: PublicReadForGetBucketObjects
          Effect: Allow
          Principal: '*'
          Action: s3:GetObject
          Resource: !Join ['', ['arn:aws:s3:::', !Ref 'WebsiteBucket', /*]]

Outputs:
  # ID:
  #   Value: !Sub "${ID}"
  #   Description: CircleCI workflow ID
  WebsiteURL:
    Value: !GetAtt WebsiteBucket.WebsiteURL
    Description: URL for website hosted on S3
    Export:
      Name: WebsiteURL
  # WebsiteARN:
  #   Value: !GetAtt WebsiteBucket.Arn
  #   Description: ARN for S3 Bucket